/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package node1;

/**
 *
 * @author oluch
 */
public class AreaScreen extends javax.swing.JFrame {

    /**
     * Creates new form AreaScreen
     */
    public AreaScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        asiaRadioButton = new javax.swing.JRadioButton();
        africaRadioButton1 = new javax.swing.JRadioButton();
        antarcticaRadioButton = new javax.swing.JRadioButton();
        nAmericaRadioButton = new javax.swing.JRadioButton();
        sAmericaRadioButton = new javax.swing.JRadioButton();
        EuropeRadioButton = new javax.swing.JRadioButton();
        australiaRadioButton = new javax.swing.JRadioButton();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Select Region for seating");

        asiaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        asiaRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        asiaRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        asiaRadioButton.setText("Asia ");

        africaRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        africaRadioButton1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        africaRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        africaRadioButton1.setText("Africa");
        africaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                africaRadioButton1ActionPerformed(evt);
            }
        });

        antarcticaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        antarcticaRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        antarcticaRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        antarcticaRadioButton.setText("Antarctica");
        antarcticaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antarcticaRadioButtonActionPerformed(evt);
            }
        });

        nAmericaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        nAmericaRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        nAmericaRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        nAmericaRadioButton.setText("North America");

        sAmericaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        sAmericaRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        sAmericaRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        sAmericaRadioButton.setText("South America");
        sAmericaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAmericaRadioButtonActionPerformed(evt);
            }
        });

        EuropeRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        EuropeRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        EuropeRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        EuropeRadioButton.setText("Europe");
        EuropeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuropeRadioButtonActionPerformed(evt);
            }
        });

        australiaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        australiaRadioButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        australiaRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        australiaRadioButton.setText("Australia");
        australiaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                australiaRadioButtonActionPerformed(evt);
            }
        });

        continueButton.setBackground(new java.awt.Color(0, 0, 0));
        continueButton.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nAmericaRadioButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(africaRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(asiaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(sAmericaRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(australiaRadioButton)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(antarcticaRadioButton)
                            .addComponent(EuropeRadioButton))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(africaRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asiaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(antarcticaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nAmericaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAmericaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EuropeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(australiaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void antarcticaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antarcticaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antarcticaRadioButtonActionPerformed

    private void sAmericaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAmericaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAmericaRadioButtonActionPerformed

    private void africaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_africaRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_africaRadioButton1ActionPerformed

    private void EuropeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuropeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EuropeRadioButtonActionPerformed

    private void australiaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_australiaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_australiaRadioButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
       FinalScreen screen4 = new FinalScreen();
       screen4.setVisible(true);
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EuropeRadioButton;
    private javax.swing.JRadioButton africaRadioButton1;
    private javax.swing.JRadioButton antarcticaRadioButton;
    private javax.swing.JRadioButton asiaRadioButton;
    private javax.swing.JRadioButton australiaRadioButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nAmericaRadioButton;
    private javax.swing.JRadioButton sAmericaRadioButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
