/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package node1;

/**
 *
 * @author oluch
 */
public class TableRequirementsScreen extends javax.swing.JFrame {

    /**
     * Creates new form TableRequirementsScreen
     */
    public TableRequirementsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        requirementsLabel = new javax.swing.JLabel();
        peopleLabel = new javax.swing.JLabel();
        babychairLabel = new javax.swing.JLabel();
        smokingLabel = new javax.swing.JLabel();
        playgroundLabel = new javax.swing.JLabel();
        peopleLabel4 = new javax.swing.JLabel();
        yesRadioButton2 = new javax.swing.JRadioButton();
        noRadioButton2 = new javax.swing.JRadioButton();
        yesRadioButton3 = new javax.swing.JRadioButton();
        yesRadioButton4 = new javax.swing.JRadioButton();
        yesRadioButton5 = new javax.swing.JRadioButton();
        noRadioButton3 = new javax.swing.JRadioButton();
        noRadioButton4 = new javax.swing.JRadioButton();
        noRadioButton5 = new javax.swing.JRadioButton();
        continueButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        requirementsLabel.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(0, 0, 0));
        requirementsLabel.setText("Table Requirements");

        peopleLabel.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        peopleLabel.setForeground(new java.awt.Color(0, 0, 0));
        peopleLabel.setText("How many people ? ");

        babychairLabel.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        babychairLabel.setForeground(new java.awt.Color(0, 0, 0));
        babychairLabel.setText("Baby chair needed ? ");
        babychairLabel.setAutoscrolls(true);

        smokingLabel.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        smokingLabel.setForeground(new java.awt.Color(0, 0, 0));
        smokingLabel.setText("Smoking area ? ");

        playgroundLabel.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        playgroundLabel.setForeground(new java.awt.Color(0, 0, 0));
        playgroundLabel.setText("Near playground (for kids) ? ");

        peopleLabel4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        peopleLabel4.setForeground(new java.awt.Color(0, 0, 0));
        peopleLabel4.setText("Near toilet (for elderly) ? ");

        yesRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        yesRadioButton2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        yesRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        yesRadioButton2.setText("yes");

        noRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        noRadioButton2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        noRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        noRadioButton2.setText("no");

        yesRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        yesRadioButton3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        yesRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        yesRadioButton3.setText("yes");

        yesRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        yesRadioButton4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        yesRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        yesRadioButton4.setText("yes");

        yesRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        yesRadioButton5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        yesRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
        yesRadioButton5.setText("yes");

        noRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        noRadioButton3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        noRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        noRadioButton3.setText("no");

        noRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        noRadioButton4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        noRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        noRadioButton4.setText("no");

        noRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        noRadioButton5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        noRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
        noRadioButton5.setText("no");

        continueButton.setBackground(new java.awt.Color(0, 0, 0));
        continueButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText("continue ");
        continueButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 13, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smokingLabel)
                            .addComponent(playgroundLabel)
                            .addComponent(peopleLabel4)
                            .addComponent(peopleLabel))
                        .addGap(190, 190, 190)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yesRadioButton2)
                                    .addComponent(yesRadioButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yesRadioButton4)
                                    .addComponent(yesRadioButton5)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noRadioButton3)
                            .addComponent(noRadioButton4)
                            .addComponent(noRadioButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(babychairLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noRadioButton2)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(requirementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(continueButton)
                        .addGap(298, 298, 298))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(requirementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLabel)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(babychairLabel)
                    .addComponent(yesRadioButton2)
                    .addComponent(noRadioButton2))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smokingLabel)
                    .addComponent(yesRadioButton3)
                    .addComponent(noRadioButton3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playgroundLabel)
                    .addComponent(yesRadioButton4)
                    .addComponent(noRadioButton4))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLabel4)
                    .addComponent(yesRadioButton5)
                    .addComponent(noRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        AreaScreen screen3 = new AreaScreen();
        screen3.setVisible(true);
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableRequirementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableRequirementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableRequirementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableRequirementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableRequirementsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel babychairLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton noRadioButton2;
    private javax.swing.JRadioButton noRadioButton3;
    private javax.swing.JRadioButton noRadioButton4;
    private javax.swing.JRadioButton noRadioButton5;
    private javax.swing.JLabel peopleLabel;
    private javax.swing.JLabel peopleLabel4;
    private javax.swing.JLabel playgroundLabel;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JLabel smokingLabel;
    private javax.swing.JRadioButton yesRadioButton2;
    private javax.swing.JRadioButton yesRadioButton3;
    private javax.swing.JRadioButton yesRadioButton4;
    private javax.swing.JRadioButton yesRadioButton5;
    // End of variables declaration//GEN-END:variables
}
